blank_issues_enabled: false
contact_links:
  - name: Gitter Community
    url: gitter.im/password-manager-one/community
    about: Talk about this repo and talk about everything not in the above templates
